name: Azure Container Apps Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yaml

  build:
    needs: test
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_LUNAR_PLAN_ADVISOR_SECRET }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: lunar
          containerAppName: lunar-app
          resourceGroup: lunar-plan-advisor
