name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
  # Every week on Sunday at 23:00
  schedule:
    - cron: "0 23 * * 0"

jobs:

  go-test:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.3'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
