name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
  # Every week on Sunday at 23:00
  schedule:
    - cron: "0 23 * * 0"

jobs:

  go-test:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  js-test:
    name: JS Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21'

    - name: Test
      run: node assets/js/calculatePlans.test.js
